os:
  - linux
#  - windows
#  - osx

arch: arm64

dist: bionic

sudo: required

language: python

python:
  - "3.8.2"

install:
  - python --version
  - pwd
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
  # - mkdir ~/.cloudmesh
  # - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-common/main/cloudmesh/etc/cloudmesh.yaml
  - cms help

script:
  - flake8 --max-line-length 124 --ignore=E722,C901 cloudmesh
  - pytest -v --capture=no tests
