dist: xenial

sudo: required

# language: python

python:
  - "3.7"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

install:
  - pip install --user pip -U
  - pwd
  - pip install --user -r requirements.txt
  - pip install --user -r requirements-dev.txt
  - pip install --user cloudmesh-common
  - pip install --user .
  - mkdir ~/.cloudmesh
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-common/master/cloudmesh/etc/cloudmesh.yaml
  - cms help

script: pytest -v tests/test_cmd5.py

